name: Build Lifesteal Plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 🔨 Build with Maven
        run: mvn package

      - name: 📦 Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: LifestealPlugin
          path: target/LifestealPlugin-1.0.jar
